---
# This play validates the entries of the SAS Viya PostgreSQL Infrastructure Data Server in inventory.ini and vars.yml
pg_required_third_party_assessment_results: []
pg_required_ansible_min_version: "2.8"
pg_required_jinja_min_version: "2.7.2"
postgres_port_numbers: []
postgres_pool_numbers: []
cps_postgres_pool_numbers: []
ha_pgpool_watch_port_numbers: []
ha_pgpool_virtual_ips: []
ha_cluster_list: []
cpsha_cluster_list: []
cps_ha_pgpool_virtual_ips: []
sasdatasvrc_hostname_unmatched: "Host names for sasdatasvrc do not match between the inventory file and vars.yml"
pgpoolc_hostname_unmatched: "Host names for pgpoolc do not match between the inventory file and vars.yml"
sasdatasvrc_node_number_instances: []
pgpoolc_pool_number_instances: []
valid_hostgroups: "sasdatasvrc pgpoolc cpsdatasvrc cpspgpoolc"
invalid_hostgroup_found: "Hostgroup(s) that are defined in vars.yml is(are) invalid"
