# file: mt-cli-delete.yml

# This is running on the CommandLine host but for this script to work it will need
# the Consul client token as well as the postgres libs available as well.

- name: "Running the sas-admin CLI to delete the tenant"
  hosts: CommandLine
  any_errors_fatal: true
  gather_facts: false
  become: false

  vars:
    tenant_offboard_conf: "{{ SASROOT }}/viya/config/tenant_onboard_{{ DEPLOYMENT_ID }}.conf"
    sas_delete_tenant: "{{ delete_tenant | default('true') }}"

  tasks:
    - name: Run the sas-admin CLI to delete the tenant
      run_once: true
      command: "{{ SASROOT }}/viya/home/bin/tenant_offboard.sh --action delete --file {{ tenant_offboard_conf }}"
      become: yes
      become_user: root
      environment:
        SAS_PROVIDER_ADMIN_PWD: '{{ provider_admin_pwd }}'
        SAS_PROVIDER_TENANT_PWD: '{{ tenant_provider_pwd }}'
      when: (sas_delete_tenant|lower == 'true')
...
