---
- name: Validate PostgreSQL user-modifiable entries in inventory.ini and vars.yml
  hosts: sas_all
  any_errors_fatal: true

  vars_files:
  - ../vars.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ orchestration_root }}/soe.yml"
      - "{{ orchestration_root }}/internal/soe_defaults.yml"

  tasks:
  - include_role:
      name: validate-postgres-rules
    when: ((inventory_hostname in groups['sasdatasvrc'] | default([])) or (inventory_hostname in groups['pgpoolc'] | default([])))
